function [bus, valid, offset] = deserializeBus_ScopeEventBus(input, offset, valid, namePrefix)
%#codegen
% DO NOT EDIT: Auto-generated by 
%   BusSerialize.writeDeserializeBusCode('ScopeEventBus')

    in = typecast(input, 'uint8');
    if nargin < 2
         offset = uint32(1);
    end
    if nargin < 3
         valid = uint8(1);
    end
    if nargin < 4
        namePrefix = uint8('');
    end
    offset = uint32(offset);

    bus = initializeBus_ScopeEventBus();
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Deserializing fixed-sized field event
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    % Checking header
    if valid == uint8(0) || offset + uint32(17 + numel(namePrefix) - 1) > numel(in)
        valid = uint8(0);
    end
    expectedHeader_event = uint8([2, 6, typecast(uint16(numel(namePrefix) + 5), 'uint8'), namePrefix, 'event', typecast(uint16(4), 'uint8'), 'enum', 8, 1])';
    for headerOffset = 1:uint32(17+numel(namePrefix)-1)
        valid = uint8(valid && in(offset+headerOffset-1) == expectedHeader_event(headerOffset));
    end
    offset = offset + uint32(17 + numel(namePrefix));

    % Establishing size
    if valid == uint8(0) || offset + uint32(2 - 1) > numel(in)
        % buffer not large enough for header
        valid = uint8(0);
        bus.event = repmat(ScopeEvent.CameraFrameEnd, [1 1]);
    else
        sz = typecast(in(offset:(offset+uint32(2-1))), 'uint16')';
        offset = offset + uint32(2);
        % check size
        if prod(sz) > uint16(14), valid = uint8(0); end
        elements = uint32(1);
        for i = 1:1
             elements = elements * uint32(sz(i));
        end
        if elements > uint32(0) && offset + uint32(elements*1 - 1) > numel(in)
            % buffer not large enough for data
            valid = uint8(0);
        end
        if valid && elements == uint32(0)
            % assigning empty value
            bus.event = repmat(ScopeEvent.CameraFrameEnd, [1 1]);
        else
            % read and typecast data
            assert(elements <= uint32(14));
            bus.event = repmat(ScopeEvent.CameraFrameEnd, [1 1]);
            if elements > uint32(0)
                coder.varsize('tempVar_event', 1);
                tempVar_event = repmat(ScopeEvent.CameraFrameEnd, [1 1]); % initialize enum to size with default
                [tempVar_event, nValues, valueValid] = semicolonDelimitedStringToEnumVector_ScopeEvent(typecast(in(offset:offset+uint32(elements*1 - 1))', 'uint8')',tempVar_event);
                bus.event = repmat(ScopeEvent.CameraFrameEnd, [1 1]);
                if nValues <= 1 && valueValid
                    bus.event(uint32(1):nValues) = tempVar_event(uint32(1):nValues);
                else
                    valid = uint8(0);
                end
                offset = offset + uint32(elements*1);
            end
        end
    end


end