function str = enumVectorToSemicolonDelimitedString_TaskState(enumVector)
% DO NOT EDIT: Auto-generated by 
%   BusSerialize.writeEnumToStringCode('TaskState')
%   Not compatible with code gen!

    valid = uint8(1);
    str = strjoin(arrayfun(@char, enumVector, 'UniformOutput', false), ';');
end