function bus = initializeBus_TaskStatisticsBus()
%#codegen
% DO NOT EDIT: Auto-generated by 
%   BusSerialize.writeInitializeBusCode('TaskStatisticsBus')

    bus.conditionBlockTrialsRemaining = uint16(0);
    bus.conditionBlocksCompleted = uint16(0);
    bus.successes = uint16(0);
    bus.failures = uint16(0);
    bus.successRate = double(0);
    bus.recentSuccessRate = double(0);

end