function bus = initializeBus_ToHostBus()
%#codegen
% DO NOT EDIT: Auto-generated by 
%   BusSerialize.writeInitializeBusCode('ToHostBus')

    bus.rigConfig = repmat(initializeBus_RigConfigBus(), [1 1]);
    bus.clock = uint32(0);
    bus.scopeState = repmat(initializeBus_MicroscopeStateBus(), [1 1]);
    bus.juiceRelease = uint8(0);
    bus.hand = repmat(initializeBus_HandOutputBus(), [1 1]);
    bus.eye = repmat(initializeBus_EyeOutputBus(), [1 1]);
    bus.analog = repmat(initializeBus_AnalogOutputBus(), [1 1]);
    bus.trialData = repmat(initializeBus_TrialDataOutputBus(), [1 1]);
    bus.condition = repmat(initializeBus_ConditionBus(), [1 1]);
    bus.taskControl = repmat(initializeBus_TaskControlBus(), [1 1]);
    bus.param = repmat(initializeBus_ParamBus(), [1 1]);
    bus.dataLoggerInfo = repmat(initializeBus_DataLoggerInfoBus(), [1 1]);
    bus.trialId = uint32(0);
    bus.taskStatistics = repmat(initializeBus_TaskStatisticsBus(), [1 1]);
    coder.varsize('bus.taskEventBuffer', 50, true);
    bus.taskEventBuffer = TaskEvent.CenterOnset;
    coder.varsize('bus.taskEventTimes', 50, true);
    bus.taskEventTimes = zeros([0 1], 'uint32');

end