function bus = initializeBus_RigInputBus()
%#codegen
% DO NOT EDIT: Auto-generated by 
%   BusSerialize.writeInitializeBusCode('RigInputBus')

    bus.rigConfig = repmat(initializeBus_RigConfigBus(), [1 1]);
    bus.clock = uint32(0);
    bus.hand = repmat(initializeBus_HandBus(), [1 1]);
    bus.eye = repmat(initializeBus_EyeInputBus(), [1 1]);
    bus.analog = repmat(initializeBus_AnalogInputBus(), [1 1]);
    bus.scopeState = repmat(initializeBus_MicroscopeStateBus(), [1 1]);
    bus.scopeTiming = repmat(initializeBus_ScopeTimingBus(), [1 1]);
    bus.mOEGFrameInfo = repmat(initializeBus_mOEGFrameInfoBus(), [1 1]);
    bus.decoderBus = repmat(initializeBus_DecoderBus(), [1 1]);

end