function bus = initializeBus_RigOutputBus()
%#codegen
% DO NOT EDIT: Auto-generated by 
%   BusSerialize.writeInitializeBusCode('RigOutputBus')

    bus.deliverJuice = uint8(0);
    coder.varsize('bus.udpToDataLogger', 100000, true);
    bus.udpToDataLogger = zeros([0 1], 'uint8');
    coder.varsize('bus.udpToDisplay', 70000, true);
    bus.udpToDisplay = zeros([0 1], 'uint8');
    coder.varsize('bus.udpToScope', 1500, true);
    bus.udpToScope = zeros([0 1], 'uint8');
    bus.scopeTrigger = uint8(0);
    coder.varsize('bus.scopeTrialInfo', 1000, true);
    bus.scopeTrialInfo = zeros([0 1], 'uint8');
    bus.TrialStart = uint8(0);
    bus.TrialEnd = uint8(0);
    bus.trialId = uint32(0);
    bus.mOEGLed470Active = uint8(0);
    bus.mOEGLed405Active = uint8(0);

end