function bus = initializeBus_HandBus()
%#codegen
% DO NOT EDIT: Auto-generated by 
%   BusSerialize.writeInitializeBusCode('HandBus')

    bus.handSource = HandSource.Mouse;
    bus.handUpdate = uint8(0);
    bus.handSeen = uint8(0);
    bus.handOnDevice = uint8(0);
    bus.handX = double(0);
    bus.handY = double(0);
    bus.handZ = double(0);
    bus.handTouching = uint8(0);
    bus.handVelocityX = double(0);
    bus.handVelocityY = double(0);
    bus.handVelocityZ = double(0);
    bus.handAccelerationX = double(0);
    bus.handAccelerationY = double(0);
    bus.handAccelerationZ = double(0);
    bus.handSpeed = double(0);
    bus.handMoving = uint8(0);

end