function bus = initializeBus_DataLoggerInfoBus()
%#codegen
% DO NOT EDIT: Auto-generated by 
%   BusSerialize.writeInitializeBusCode('DataLoggerInfoBus')

    coder.varsize('bus.dataStore', 30, true);
    bus.dataStore = uint8([84;101;115;116;83;116;111;114;101]);
    coder.varsize('bus.subject', 30, true);
    bus.subject = uint8([84;101;115;116;83;117;98;106;101;99;116]);
    coder.varsize('bus.protocol', 30, true);
    bus.protocol = uint8([84;101;115;116;80;114;111;116;111;99;111;108]);
    bus.protocolVersion = uint32(20140101);
    bus.saveTag = uint32(1);

end