function bus = initializeBus_DataLoggerNextTrialBus()
%#codegen
% DO NOT EDIT: Auto-generated by 
%   BusSerialize.writeInitializeBusCode('DataLoggerNextTrialBus')

    bus.nextTrial = uint32(0);

end