function bus = initializeBus_MouseInputBus()
%#codegen
% DO NOT EDIT: Auto-generated by 
%   BusSerialize.writeInitializeBusCode('MouseInputBus')

    bus.update = uint8(0);
    bus.mouseX = double(0);
    bus.mouseY = double(0);
    bus.mouseVelX = double(0);
    bus.mouseVelY = double(0);
    bus.mouseClick = uint8(0);

end