function bus = initializeBus_TaskControlBus()
%#codegen
% DO NOT EDIT: Auto-generated by 
%   BusSerialize.writeInitializeBusCode('TaskControlBus')

    bus.runTask = uint8(0);
    bus.saveData = uint8(0);
    bus.controlImaging = uint8(1);
    bus.imageEveryNthTrial = double(1);
    bus.autoTimeoutActive = uint8(0);
    bus.endTimeoutNow = uint8(0);
    bus.giveFreeJuice = uint8(0);
    bus.resetConditionBlock = uint8(0);
    bus.flushJuice = uint8(0);
    bus.resetStats = uint8(0);

end