function bus = initializeBus_AnalogInputBus()
%#codegen
% DO NOT EDIT: Auto-generated by 
%   BusSerialize.writeInitializeBusCode('AnalogInputBus')

    bus.photoboxRaw = double(0);
    bus.photobox = uint8(0);

end