function bus = initializeBus_TrialDataOutputBus()
%#codegen
% DO NOT EDIT: Auto-generated by 
%   BusSerialize.writeInitializeBusCode('TrialDataOutputBus')

    bus.rt = uint32(0);
    bus.delay = uint32(0);
    bus.iti = uint32(0);
    bus.success = uint8(0);
    bus.substantiveFailure = uint8(0);
    bus.failureCode = TaskState.TaskPaused;
    bus.consecutiveNoStarts = uint16(0);
    bus.inPurgatory = uint8(0);
    bus.purgatoryTimeRemaining = uint32(0);
    bus.holdXCenter = double(0);
    bus.holdYCenter = double(0);
    bus.holdXTarget = double(0);
    bus.holdYTarget = double(0);
    bus.decodeSuccess = uint8(0);
    bus.isDecodeCondition = uint8(0);

end