function [enumValue, valid] = stringToEnum_TaskEvent(str)
%#codegen
% DO NOT EDIT: Auto-generated by 
%   BusSerialize.writeEnumToStringCode('TaskEvent')

    valid = uint8(1);
    if isequal(uint8(str(:)), uint8('CenterOnset')')
        enumValue = TaskEvent.CenterOnset;
    elseif isequal(uint8(str(:)), uint8('CenterAcquired')')
        enumValue = TaskEvent.CenterAcquired;
    elseif isequal(uint8(str(:)), uint8('CenterUnacquired')')
        enumValue = TaskEvent.CenterUnacquired;
    elseif isequal(uint8(str(:)), uint8('CenterSettled')')
        enumValue = TaskEvent.CenterSettled;
    elseif isequal(uint8(str(:)), uint8('CenterHeld')')
        enumValue = TaskEvent.CenterHeld;
    elseif isequal(uint8(str(:)), uint8('TargetOnsetCommand')')
        enumValue = TaskEvent.TargetOnsetCommand;
    elseif isequal(uint8(str(:)), uint8('GoCueCommand')')
        enumValue = TaskEvent.GoCueCommand;
    elseif isequal(uint8(str(:)), uint8('GoCue')')
        enumValue = TaskEvent.GoCue;
    elseif isequal(uint8(str(:)), uint8('TargetOnset')')
        enumValue = TaskEvent.TargetOnset;
    elseif isequal(uint8(str(:)), uint8('MoveOnsetOnline')')
        enumValue = TaskEvent.MoveOnsetOnline;
    elseif isequal(uint8(str(:)), uint8('MoveOnsetThresh')')
        enumValue = TaskEvent.MoveOnsetThresh;
    elseif isequal(uint8(str(:)), uint8('TargetAcquired')')
        enumValue = TaskEvent.TargetAcquired;
    elseif isequal(uint8(str(:)), uint8('TargetUnacquired')')
        enumValue = TaskEvent.TargetUnacquired;
    elseif isequal(uint8(str(:)), uint8('TargetSettled')')
        enumValue = TaskEvent.TargetSettled;
    elseif isequal(uint8(str(:)), uint8('TargetHeld')')
        enumValue = TaskEvent.TargetHeld;
    elseif isequal(uint8(str(:)), uint8('ReachEnd')')
        enumValue = TaskEvent.ReachEnd;
    elseif isequal(uint8(str(:)), uint8('Success')')
        enumValue = TaskEvent.Success;
    elseif isequal(uint8(str(:)), uint8('FailureToAcquireCenter')')
        enumValue = TaskEvent.FailureToAcquireCenter;
    elseif isequal(uint8(str(:)), uint8('FailureBrokeCenterHold')')
        enumValue = TaskEvent.FailureBrokeCenterHold;
    elseif isequal(uint8(str(:)), uint8('FailureBrokeCenterHoldDelay')')
        enumValue = TaskEvent.FailureBrokeCenterHoldDelay;
    elseif isequal(uint8(str(:)), uint8('FailureRTTooFast')')
        enumValue = TaskEvent.FailureRTTooFast;
    elseif isequal(uint8(str(:)), uint8('FailureRTTooSlow')')
        enumValue = TaskEvent.FailureRTTooSlow;
    elseif isequal(uint8(str(:)), uint8('FailureToAcquireTarget')')
        enumValue = TaskEvent.FailureToAcquireTarget;
    elseif isequal(uint8(str(:)), uint8('FailureBrokeTargetHold')')
        enumValue = TaskEvent.FailureBrokeTargetHold;
    elseif isequal(uint8(str(:)), uint8('FailureLowPeakVelocity')')
        enumValue = TaskEvent.FailureLowPeakVelocity;
    elseif isequal(uint8(str(:)), uint8('FailureHandNotSeen')')
        enumValue = TaskEvent.FailureHandNotSeen;
    elseif isequal(uint8(str(:)), uint8('DecodeComplete')')
        enumValue = TaskEvent.DecodeComplete;
    else
        enumValue = TaskEvent.CenterOnset;
        valid = uint8(0);
    end
end