function [enumValue, valid] = stringToEnum_TrialCategory(str)
%#codegen
% DO NOT EDIT: Auto-generated by 
%   BusSerialize.writeEnumToStringCode('TrialCategory')

    valid = uint8(1);
    if isequal(uint8(str(:)), uint8('Unknown')')
        enumValue = TrialCategory.Unknown;
    elseif isequal(uint8(str(:)), uint8('TargetOnly')')
        enumValue = TrialCategory.TargetOnly;
    elseif isequal(uint8(str(:)), uint8('CenterOut')')
        enumValue = TrialCategory.CenterOut;
    else
        enumValue = TrialCategory.Unknown;
        valid = uint8(0);
    end
end